apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: my-super-secret-auth-token
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: mybucket
      tlsSkipVerify: true
    editable: true 